version: "3.8"

services:
  todo_backend:
    container_name: todo_backend
    build: ./todo-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./todo-backend:/app
    depends_on:
      - db
      - pgadmin
    environment:
      SQL_DIALECT: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: postgres
      DATABASE_HOST: db
  
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test1
    logging:
      driver: none
    depends_on:
      - db
    ports:
      - "5050:80"

  todo_frontend:
    build: ./todo-frontend
    container_name: todo_frontend
    depends_on:
      - todo_backend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      BASE_API_URL: http://todo_backend:5000
    logging:
      driver: none

volumes:
  db_data:
